name: ExecuteTests
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
    build:
      runs-on: [ ubuntu-latest ]
      #runs-on: [DCMTPVMTFS015]
      #timeout-minutes: 2
      steps:
        - name: BrowserStack Action
          uses: 'browserstack/github-actions/setup-env@master'
          with:
            username:  test
            access-key: test1234

